### ISSUE TITLE
Collections page option

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#104]
Hey, Steven.
Would it be possible to add an alphabetical navigation option to the top of the browse Collections page? Since we have so many collections now, it seems like we should probably do something to make that page a little more user friendly. Obvious not a pressing issue, and I would welcome your thoughts if you have other ideas.
Thanks!

**Comment by scande3** [comment]
Do you mean something similar to what exists on Digital Commonwealth? Essentially: https://www.digitalcommonwealth.org/collections ?

Are there other things that could be useful to filter on that collection page beyond alphabetical navigation? One thing that we have struggled with in Digital Commonwealth is that as collections increased, finding a collection has been more difficult since one doesn't always know what it starts with. Not sure what else might be useful that wouldn't be overwhelming to limit by?

**Comment by kjrawson** [comment]
Yes, something like that. I've been trying to brainstorm other ways of filtering and I can't think of anything, either. I agree that alphabetical seems arbitrary. We could also add a few pages to it so that it isn't a single scroll, but that will probably curtail some of the benefits of browsing. The students have been talking about creating themes to bring together collections, too, but they keep coming up with genre-based themes, which would be redundant.

**Comment by kjrawson** [comment]
Looks great!
