### ISSUE TITLE
Uploading errors

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#106]
Here's a report from a student about an issue they've been having:

![screen shot 2017-03-22 at 12 49 51 pm](https://cloud.githubusercontent.com/assets/15388345/24214914/672eea98-0f0d-11e7-9a97-1b847d9b41ea.png)
![screen shot 2017-03-22 at 12 49 55 pm](https://cloud.githubusercontent.com/assets/15388345/24214918/6954e61a-0f0d-11e7-9f71-8e2748e35bee.png)

We were having a recurring issue where, when we would try to save a processed photograph, the above message would show up. If we refreshed the page, the next message would appear.
To fix this, we would hit the back button on the browser. Most of the data would be saved, but a few Homosaurus terms would be missing, so we would just add those back in. We would also have to click on the institution a few times to make the collection pop back up, if that makes sense. The item would immediately upload the second time we tried, however.

**Comment by scande3** [comment]
Has there been more reported cases of this error?

**Comment by kjrawson** [comment]
No, not this one exactly. But, there have been issues with files not always saving. And more often than not, when a file saves we need to regenerate the thumbnail for it to appear.

**Comment by scande3** [comment]
One possibility is upgrading from Fedora Commons 4.7.0 to Fedora Commons 4.7.1 as it does have some bug fixes: https://wiki.duraspace.org/display/FF/Fedora+4.7.1+Release+Notes

I can't reproduce it locally otherwise. Some possibilities beyond the above:
1. Send me the url of an item that failed to save (assuming it has the identifier in the url) to check if anything of it persisted. If it is the thumbnail, leave one without the regenerate command to look at.

2. If it is happening quite frequently (1+ times a session), could try to schedule time for me to come in to watch the work being which might allow me to spot what might be causing the effect.

Thanks!

**Comment by kjrawson** [comment]
I am thinking that an update might be best, if it's not too onerous...

**Comment by scande3** [comment]
Fedora was upgraded to the latest version over the weekend. Let me know if these issues still occur. Thanks!

**Comment by kjrawson** [comment]
Great...thanks!
