### ISSUE TITLE
Institution view error

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#111]
Hi, Steven.
I am experiencing a random back-end error that I wanted to let you know about. When I navigate to Browse>Institutions>Transas City>View all items, I get the message below. The good news is that it doesn't seem to happen on the front end when not logged in, just the back end. Just figured you'd like to know.
![transas](https://cloud.githubusercontent.com/assets/15388345/26808690/a5d71630-4a2c-11e7-9a16-607cb21baa57.jpeg)

**Comment by scande3** [comment]
I have a theory regarding this but want to verify: did you delete an item from the Transas City Institution recently?

**Comment by kjrawson** [comment]
I did delete some sample records that we never intended to make public. Might that have had an impact?

**Comment by scande3** [comment]
Alright, I'll look into it this weekend. The issue is likely that the Solr caching record failed to be deleted when the ActiveFedora object was removed. So it is trying to load an object to display that no longer exists. It isn't hard to fix - but I'll have to try to duplicate the state first to figure out why it occurred.

Mostly just wanted to verify deletes had been done rather than objects just going missing. Thanks!

**Comment by kjrawson** [comment]
Perfect––thanks, Steven!

**Comment by scande3** [comment]
This should be corrected now. If it occurs again, let me know, but I think this was just an artifact of how I handled putting Solr back to a normal state where I didn't take into account you might have deleted objects during that first week of normal operation.

**Comment by kjrawson** [comment]
Perfect––thank you!
