### ISSUE TITLE
Deleting a collection

### ISSUE THREAD

**Issue by ntantum** [CollegeOfTheHolyCross/dta_sufia#121]
Hi Steven!

I have been trying to delete an empty collection for the past couple of days but I keep getting an error message.
Collection I am trying to delete: [https://www.digitaltransgenderarchive.net/collections/wm117p22r](https://www.digitaltransgenderarchive.net/collections/wm117p22r)
Error message: [https://www.digitaltransgenderarchive.net/collections/wm117p22r](https://www.digitaltransgenderarchive.net/collections/wm117p22r)

The collection is not public so this is not super urgent but I will let you know if I have any additional issues deleting items in the future!

**Comment by scande3** [comment]
The error is due to me disabling the collection delete functionality in the last update. Deleting a collection would not delete all of the items in that collection... which meant items without a collection would be left in the system. Logic to handle this case needs to be applied to prevent this case from occurring.

This functionality should be re-enabled this weekend along with improvements to collection stability as I finish a review of how those methods are working.

(Also: in the future, is it possible to capture screenshots of error messages? The link above is just for the show page of the collection).

Thanks!

**Comment by scande3** [comment]
@ntantum -> You should be able to delete these now. Let me know if you see an issue. Thanks!

**Comment by ntantum** [comment]
It worked! Thank you!
