### ISSUE TITLE
Thumbnails linking to objects hosted elsewhere (high priority)

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#20]
Here's the collection we want to include information for:

http://digital.utsa.edu/cdm/search/collection/p15125coll9/searchterm/linda%20and%20cynthia%20phillips/field/all/mode/all/conn/and/order/nosort

**Comment by scande3** [comment]
Initial functionality for this has been added but is a tad rough. Let me know how it functions. Of note:

1. You can upload an image, a PDF, or a word document in the file field. It will only create a thumbnail for that and won't store the original file (assuming you have checked that it is hosted elsewhere).

2. Images are optional when an item is hosted elsewhere in case a thumbnail doesn't exist for some reason. It is recommended to not skip a thumbnail when possible to use one. Can still force the thumbnail image if needed.

3. Editing should work but do not upload a new image when editing an item just yet. If the creation workflow seems to work, I can fix it so that an image uploaded when editing has the same workflow as step 1.

Commit: ba775c37dc55abe13fd7f99db31ed40df5b2a998

**Comment by kjrawson** [comment]
Well done!! I just created one sample to see how it works: "Reed Erickson with Family." Seems perfect! See how you like it.

I am thinking that a thumbnail will always exist, but thanks for clarifying the second point. The workflow seems like it will be fine. I'll keep this open until we hit it harder in the coming week or two, in case any changes come up.
