### ISSUE TITLE
Explicit content warning moved {On hold until K.J. figures it out}

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#35]
When the thumbnail isn't explicit, could the explicit content warning be moved so that it comes up when a person tries to open the file rather than simply looking at the record? Thank you!

**Comment by kjrawson** [comment]
You've already done this, but we needed a placeholder image for when there is explicit content in a thumbnail. Thanks!

**Comment by scande3** [comment]
Trying to implement this has proven to be somewhat difficult. The question deals with the various ways one can interact with the file. For example, what happens when they right-click and choose to save the file? Or is it that there is no link to the full file until they accept a warning? In that latter case, is the thumbnail not clickable as well until such warning is accepted?

**Comment by kjrawson** [comment]
I can see how this got difficult. I suppose you are right that nothing beyond the thumbnail should be clickable until the warning is accepted. Does that make it too difficult to implement?
