### ISSUE TITLE
Minor issue with one collection

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#46]
From a student:
I looked back into the problem and it only appears to be happening in the Fantasia Fair: Misc Collection. It's a front-end issue. When you go to the collection and view all of the materials, the "Next" button never (for lack of a better word) "dies." As in, you can keep pressing next and getting to the next blank page. I poked around and this is not a general problem, just specific to this collection as far as I can tell.

**Comment by scande3** [comment]
This should now be fixed in the current commit and the "Next" button should be disabled when there are no more next pages to go to. This was done in commit 3c71454265eb13806e700061928bf45376589b35 . 

(For anyone in the future: essentially it was a bug in Sufia 6.x's override of Blacklight. As such, the blacklight files for the pagination were copied locally to override Sufia's changes to it).

**Comment by kjrawson** [comment]
It looks like the button is disabled (it's gray and there's a hover-over caution sign that pops up), but you can still click it and get through to subsequent blank pages. https://www.digitaltransgenderarchive.net/catalog?f%5Bcollection_name_ssim%5D%5B%5D=Fantasia+Fair%3A+Miscellaneous+Documents&page=7

**Comment by kjrawson** [comment]
It appears that you can still click on "Next" in other collections and search results as well––it's not just that one collection.

**Comment by scande3** [comment]
Ah, hadn't actually tried to click it when it was disabled. Try it again now? (Commits b5b844976b8aef3e725ec102ebb69e639a08ed2c and c4612a63e4bf5d19ee03a641c27f8c30f38de803 ).

**Comment by kjrawson** [comment]
Perfect––fixed! Thank you!
