### ISSUE TITLE
Downloading different file type

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#94]
This isn't much of an issue, but I just noticed that my browser (Chrome) is treating the file associated with this record differently: https://www.digitaltransgenderarchive.net/files/cv43nw890. Perhaps because it is a tiff file? It's doing a direct download rather than opening it up in a separate tab. Thanks!

**Comment by scande3** [comment]
TIFF files are only supported in Safari at the moment. Since Chrome cannot display it natively, it does indeed download the file instead.

For Digital Commonwealth, we actually store master TIFF files (which can now be downloaded for BPL collections, see: https://www.digitalcommonwealth.org/search/commonwealth:4j03d910t for an example) and derivative JP2 images created from that TIFF for deep zoom browsing. This could potentially be done for the Digital Transgender Archive at some point?

**Comment by kjrawson** [comment]
Yes, that would be great. Not a major priority, but perhaps something we can return to soon. Thanks!

**Comment by scande3** [comment]
This should now be resolved with the new image server and image viewer (backported into the existing application and part of the new system).

**Comment by scande3** [comment]
Scratch that for a minute. There is a port issue where it doesn't resolve off the DTA network. Will communicate with Rick about it.

**Comment by scande3** [comment]
This should now fully be complete and resolved.

**Comment by kjrawson** [comment]
Looks great––thank you!!!
